version: '3'
services:
  web:
    build: .
    env_file:
      - env.list
    ports:
      - '8888:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'